#file: noinspection undefined
server:
  port: 7073
  servlet:
    context-path: /notification

spring:
  application:
    name: notification-service
  data:
    mongodb:
      uri: mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@${MONGODB_HOST}:${MONGODB_PORT}/notification-service?authSource=admin
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS_HOST}:${KAFKA_BOOTSTRAP_SERVERS_PORT}
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.anonymousv18.event.dto"
        spring.json.use.type.headers: false
        spring.json.value.default.type: "com.anonymousv18.event.dto.NotificationEvent"

notification:
  brevo:
    url: ${BREVO_API_URL}
    api-key: ${BREVO_API_KEY}